### PR TITLE
Update to rusqlite 0.29

### PR DESCRIPTION
**Pull request by johnbcodes**
Thank you for creating this library.

Has ownership been transferred yet? I'm willing to take over if not.

### CODE REVIEW

**Comment by felipelalli** [comment]
Please, give an attention on this. @ivanceras

**Comment by johnbcodes** [comment]
To others who want to move forward @jerebtw has [created](https://crates.io/crates/r2d2_sqlite_pool) a [fork](https://github.com/jerebtw/r2d2-sqlite) that includes #45 and resolves this and #49

**Comment by felipelalli** [comment]
@johnbcodes but how to include this on Cargo.toml ? (Sorry, I'm newbie on Rust).

**Comment by johnbcodes** [comment]
No worries, the link to crates.io I included has what you need. In this case, add the following or replace the `r2d2_sqlite` entry in Cargo.toml with:

`r2d2_sqlite_pool = "0.1.1"`

**Comment by felipelalli** [comment]
Ah! OK! I thought it wasn't published yet.

**Comment by ivanceras** [comment]
Apology for not paying attention to this much sooner. I've added @johnbcodes and @jerebtw in this repo as collaborator.

**Comment by antimora** [comment]
@ivanceras Since this has been merged, can we have an updated release? The main branch version says it's the 0.21.0 which is released but does not have this fix. Thank you!

**Pull request merged**
