### PR TITLE
Clean up and minor refactoring

### PR DESCRIPTION
**Pull request by dippi**
Clean repository and code, add documentation, update versions.
Refactors SqliteConnectionManager construction.

### CODE REVIEW

**Comment by ivanceras** [comment]
Thanks,

**Comment by dippi** [comment]
Could you update the docs on gh-pages?
Maybe you can automate doc publishing (and perhaps also crates.io publishing) with travis, googling it up I found many guides to do so.

**Comment by ivanceras** [comment]
Just updated the docs and added the link in the Readme 
http://ivanceras.github.io/r2d2-sqlite/r2d2_sqlite/

Thanks again.

**Comment by dippi** [comment]
You're welcome and thanks to you for mantaining it!

**Pull request merged**
